settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: ygp-api
  path: .
  commands:
    install:
      status: true
      method: go build -o ./bin/app
    run:
      status: true
      method: ./bin/app
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
