settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: psutils
  path: .
  commands: {}
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
      - vendor
